[package]
name = "bevy-demo"
version = "0.1.0"
authors = ["floppyhammer <tannhauser_chen@outlook.com>"]
edition = "2021"
rust-version = "1.61.0"

[dependencies]
bevy = "0.8.0"
bevy-inspector-egui = "0.12.1"
bevy_egui = "0.15.1"
