[package]
name = "bevy-demo"
version = "0.1.0"
authors = ["floppyhammer <tannhauser_chen@outlook.com>"]
edition = "2021"
rust-version = "1.65.0"

[dependencies]
bevy = "0.9.0"
bevy-inspector-egui = "0.14"
